### ISSUE TITLE
InputDataError on getReport

### ISSUE THREAD

**Issue by muhammadali7768** [ScaleLeap/amazon-mws-api-sdk#320] opened 2021-03-02 15:25 UTC
i am trying to get the `_RFQD_BULK_DOWNLOAD_` type report using the getReport() method.
```
 const [response] = await reports.getReport({
      ReportId: "27533305591018684"
    })
```
i tried different report types but i am getting the **InputDataError** for all types.
```
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  type: 'Sender',
  code: 'InputDataError',
  detail: '',
  mwsMessage: 'InputDataError',
  requestId: 'bdaf89d1-027c-4e77-8385-e03e5a616789'
}
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type object
    at Function.from (buffer.js:293:9)
    at post$b (/myProjec/__sapper__/dev/server/server.js:1557:29)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by moltar** [comment] 2021-03-02 15:40
Please take a look at the docs for the correct invocation signature.

**Comment by moltar** [comment] 2021-03-02 15:42
Oops looks like the docs are wrong. Will look into this tomorrow.

**Comment by muhammadali7768** [comment] 2021-03-02 16:42
> Please take a look at the docs for the correct invocation signature.

When i try like this 
`
  const [response] = await reports.getReport("27533305591018684")`

i am getting this error
request error <?xml version="1.0"?>
`<ErrorResponse xmlns="http://mws.amazonaws.com/doc/2009-01-01/"><Error><Type>Sender</Type><Code>MissingParameter</Code><Message>The request must contain the parameter ReportId.</Message><Detail/></Error><RequestID>40ac08f4-7c91-409c-9e62-3aa179d61d3c</RequestID></ErrorResponse>`

**Comment by moltar** [comment] 2021-03-03 00:45
Are you sure you are using the right `ReportId` value? There are [quite a few reports](https://sellercentral.amazon.com/forums/search?q=InputDataError) of the same issue on the support forums.

We have an integration test for this call and it seems to work fine. I am not saying this is not a bug, it might as well still be. But I am just pointing out some hints that maybe you can use to debug this, as I cannot reproduce this on my own.

https://github.com/ScaleLeap/amazon-mws-api-sdk/blob/2f9f81c0418bbda468f1c9e8ba30483406fc25f3/test/integration/reports.test.ts#L118-L125

**Comment by muhammadali7768** [comment] 2021-03-03 03:53
> Are you sure you are using the right `ReportId` value? There are [quite a few reports](https://sellercentral.amazon.com/forums/search?q=InputDataError) of the same issue on the support forums.

I am passing the `GeneratedReportId` value to getReport.
```

{
  HasNext: false,
  ReportRequestInfo: {
    ReportRequestId: '497464018689',
    ReportType: '_RFQD_BULK_DOWNLOAD_',
    StartDate: 2021-03-03T03:08:48.000Z,
    EndDate: 2021-03-03T03:08:48.000Z,
    Scheduled: false,
    SubmittedDate: 2021-03-03T03:08:48.000Z,
    ReportProcessingStatus: '_DONE_',
    GeneratedReportId: '27702597267018690',
    StartedProcessingDate: 2021-03-03T03:08:52.000Z,
    CompletedDate: 2021-03-03T03:08:59.000Z
  }
}

{
  HasNext: false,
  ReportRequestInfo: {
    ReportRequestId: '497465018689',
    ReportType: '_RFQD_BULK_DOWNLOAD_',
    StartDate: 2021-03-03T03:10:21.000Z,
    EndDate: 2021-03-03T03:10:21.000Z,
    Scheduled: false,
    SubmittedDate: 2021-03-03T03:10:21.000Z,
    ReportProcessingStatus: '_DONE_',
    GeneratedReportId: '27700872951018690',
    StartedProcessingDate: 2021-03-03T03:10:26.000Z,
    CompletedDate: 2021-03-03T03:10:32.000Z
  }
}
```

**Comment by moltar** [comment] 2021-03-03 06:01
I just added some docs for MITM proxy: https://github.com/ScaleLeap/amazon-mws-api-sdk/blob/master/CONTRIBUTING.md#debugging-using-a-mitm-proxy

Please do that to inspect the HTTP traffic and see what is being returned.

Please post the response HTTP headers here.

And let me know if the response is binary.

**Comment by muhammadali7768** [comment] 2021-03-04 03:08
These are the request and response headers.

![mmexport1614802497032](https://user-images.githubusercontent.com/34996563/109905423-93ca3600-7cc0-11eb-8e09-0b8ad90bd1a0.jpg)

**Response:**
![mmexport1614802507072](https://user-images.githubusercontent.com/34996563/109905441-99278080-7cc0-11eb-91b0-a12364781acc.jpg)

**Comment by moltar** [comment] 2021-03-04 03:29
Ok, great, thanks. That looks fine to me.

What about the request body itself? Can you please add that here as well?

Thanks.

**Comment by muhammadali7768** [comment] 2021-03-04 08:37
> What about the request body itself? Can you please add that here as well?

Thanks for pointing me in the right direction and your quick responses. When i checked the request body, the MWSAuthToken was set to undefined. I set the **MWSAuthToken** to correct value, now i am getting the .xlsx file in response. But i am unable to get the correct .xlsx file.
This the response after setting the **MWSAuthToken** correctly.
![Screenshot from 2021-03-04 13-03-21](https://user-images.githubusercontent.com/34996563/109933611-71024680-7ced-11eb-86d2-238ac4f1d2cc.png)


I am checking the file type using **file-type** package.
`console.log(await FileType.fromBuffer(Buffer.from(response)));`
i am getting the following output in the console.
```
{
  ext: 'xlsx',
  mime: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
}
```

When i write the file using the following method the xlsx file is empty.
```
 var data = new Uint8Array(Buffer.from(response));
       var workbook = XLSX.read(data, {type:"array"});
  XLSX.writeFile(workbook, 'out.xlsx');
```

I tried the following method too but didn't work.

```
 const workbook=	XLSX.read(Buffer.from(response))
     let worksheets = workbook.SheetNames.map(sheetName => {
    	return { sheetName, data: XLSX.utils.sheet_to_json(workbook.Sheets[sheetName]) };
    });
```
Please help me with this issue.

**Comment by moltar** [comment] 2021-03-04 10:13
I am glad the original issue was solved.

Unfortunately I am not familiar with the library you are using for XLS management and cannot help.

I will close the issue, as the original issue seems to be solved.

**Closed by moltar** 2021-03-04 10:13 UTC
